const puppeteer = require('puppeteer')
const screenshot = 'restart.png';
(async () => {
  console.log('start...')
  const browser = await puppeteer.launch({ headless: true, defaultViewport: null, args: ['--start-maximized'] })
  const page = await browser.newPage()
  console.log('open browser...')
  await page.goto('http://192.168.1.1/')
  await page.type('#password', 'yourPass')
  await page.click('[id="loginbtn"]')
  await page.waitForNavigation()
  console.log('logged...')
  await page.goto('http://192.168.1.1/html/advance.html#device_mngt')
  await page.waitForTimeout(1000)
  await page.click('#rebootId')
  await page.waitForTimeout(1000)
  console.log('reboot')
  await page.click('#dev_mngt_modal_id_ok')
  await page.waitForTimeout(1000)
  browser.close()
  console.log('ok... 0-0-')
  //console.log('See screenshot: ' + screenshot)
})()